spring:
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:h2:./database;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
  flyway:

  config:
    name: Zwie
