name: Commit

on:
  push:
    branches-ignore:
      - 'gh-pages'
#  pull_request:


env:
  CARGO_TERM_COLOR: always

jobs:
  build-client:
    strategy:
      fail-fast: true
      matrix:
        platform: [ macos-latest, ubuntu-latest] #  ,windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@6c561573985cd8bd4d64efcfe270d51682d210e2
      - name: Add aarch64-apple-darwin
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin
      - name: Install dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      #    - name: Install dependencies (macos)
      #      if: matrix.platform == 'macos-latest'
      #      run: |
      #         brew install dbus
      - name: Build Cache (gradle)
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: |
            **/build/
            client/src-tauri/target
            !client/src-tauri/target/*/bundle/**
            client/node_modules
          key: ${{ runner.os }}-client
          #key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts','settings.gradle.kts','client/yarn.lock','client/src-tauri/Cargo.lock') }}-client
      - name: Run Build Web
        run: ./gradlew client:build
      # TODO: Run tests
      - name: Stop Gradle
        run: ./gradlew --stop

      - name: Build Client (${{ matrix.platform }})
        if: matrix.platform != 'macos-latest'
        working-directory: ./client
        run: yarn tauri build --debug
      - name: Build Client (macos)
        if: matrix.platform == 'macos-latest'
        working-directory: ./client
        run: yarn tauri build --debug --target universal-apple-darwin
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@6c561573985cd8bd4d64efcfe270d51682d210e2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build Cache
        id: cache-primes
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: |
            **/build/
          key: ${{ runner.os }}-server
      - name: Run Build
        run: ./gradlew server:build
      - name: Run Test
        run: ./gradlew server:test
      - name: Stop Gradle
        run: ./gradlew --stop