name: Build Pages

on:
  push:
    branches:
      - main


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: pages-${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@6c561573985cd8bd4d64efcfe270d51682d210e2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: |
            client/node_modules
          key: ${{ runner.os }}-${{ hashFiles('client/yarn.lock','client/src-tauri/Cargo.lock') }}-client
      - run: ./gradlew client:build-web
        name: Build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/build
          clean: true
      - name: Stop Gradle
        run: ./gradlew --stop